name = "LabDataSources"
uuid = "3f048c1c-c20e-472f-bb30-3059a370834e"
authors = ["Allen Hill <allenofthehills@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
